# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Financial App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Financial App

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Firestore'
pod 'SDWebImage/WebP'

end
